name: Deploy Distribution
on: [push,workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: "Get Code"
              run: | 
                echo "Cloneing repository..."
                echo "${{toJson(github)}}"
                git clone https://github.com/${{github.repository}}.git
            - name: "Install Node.js"
              run: node -version || echo "Node.js not found"
                echo "Atul Joshi Is Using Github Actions"